### ISSUE TITLE
This beeg emu is lacking beeg yoshi

### ISSUE THREAD

**Issue by bigbass1997** [ITotalJustice/notorious_beeg#92]
![beeg_bold](https://cdn.discordapp.com/emojis/739301288344420463.webp?size=96&quality=lossless)

> TotalJustice: I would love to have issues opened on my repos by someone other than me

**Comment by Dillonb** [comment]
I am also experiencing this issue.

Repro steps:

1. Download emulator
2. Run emulator
3. No beeg yoshi
